# config.yaml

aws:
  account_id: "581867121448"
  region: "us-east-1"
  work_bucket: "vastra"

queues:
  segmentation:   "vastra-dev-segmentation"
  analysis:       "vastra-dev-analysis"
  identification: "vastra-dev-identification"
  vton:           "vastra-dev-vton"
  dlq:            "vastra-dev-dlq"

steps:
  SEGMENTATION:
    filetype: "png"
    extensions: [".png"]
    hooks_path: "services.cloth_segmentation.hooks.Hooks"
    next:
      - ANALYSIS
    queue: "segmentation"

  ANALYSIS:
    filetype: "json"
    extensions: [".json"]
    hooks_path: "services.cloth_analysis.hooks.Hooks"
    queue: "analysis"

  ENHANCEMENT:
    filetype: "png"
    extensions: [".png"]
    hooks_path: "services.cloth_enhancement.hooks.Hooks"
    next:
      - SEGMENTATION
    queue: "identification"

  VIRTUAL_TRY:
    filetype: "png"
    extensions: [".png", ".jpg", ".jpeg"]
    hooks_path: "services.virtualtry.hooks.Hooks"
    queue: "vton"
