apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "worker-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "worker-chart.name" . }}
    spec:
      serviceAccountName: {{ include "worker-chart.serviceAccountName" . }}
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ include "worker-chart.fullname" . }}-config
        - secretRef:
            name: {{ include "worker-chart.fullname" . }}-secrets

